import java.util.Random;
import java.util.Scanner;

public class NumberGuessingGame {
    private static final int MAX_ATTEMPTS = 5;
    private static final int MAX_ROUNDS = 3;
    private static final int RANGE = 100;

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int score = 0;

        System.out.println("Welcome to the Number Guessing Game!");
        System.out.println("You need to guess the number generated by the system between 1 and " + RANGE);

        for (int round = 1; round <= MAX_ROUNDS; round++) {
            System.out.println("\n--- Round " + round + " ---");
            int roundScore = playRound(scanner);
            score += roundScore;
            System.out.println("Round " + round + " Score: " + roundScore);
        }

        System.out.println("\nGame Over! Your Total Score: " + score);
        scanner.close();
    }

    private static int playRound(Scanner scanner) {
        Random random = new Random();
        int targetNumber = random.nextInt(RANGE) + 1;
        int attempts = 0;
        int roundScore = 0;

        System.out.println("Guess the number between 1 and " + RANGE);

        while (attempts < MAX_ATTEMPTS) {
            System.out.print("Enter your guess: ");
            int guess = scanner.nextInt();
            attempts++;

            if (guess == targetNumber) {
                System.out.println("Congratulations! You guessed the correct number.");
                roundScore = (MAX_ATTEMPTS - attempts + 1) * 10; // Higher points for fewer attempts
                break;
            } else if (guess < targetNumber) {
                System.out.println("Your guess is too low.");
            } else {
                System.out.println("Your guess is too high.");
            }

            System.out.println("Attempts left: " + (MAX_ATTEMPTS - attempts));
        }

        if (attempts == MAX_ATTEMPTS && roundScore == 0) {
            System.out.println("Out of attempts! The correct number was: " + targetNumber);
        }

        return roundScore;
    }
}
